CMPUT301F21T09/BudgetProjectName

doc/team.txt

Add team.txt with my information

Add team.txt

---

doc/team.txt

Added ccid and git user to team.txt

Added to team.txt

---

src/app/build.gradle

Add firestore

---

src/app/src/main/AndroidManifest.xml
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ExampleActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventModel.java

Saving newly added / edited HabitEvent (as a document) to a Firestore collection. 
I'm not sure if I should move these functions to a "Store" class as per our Model-View-Store model proposal.
Tests will be added once this is settled on.
Created functions for creating, reading, and updating HabitEvent using Firestore.
**Need to add a check if the description is 20 chars**

Habitevent firestore

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java

There was a mismatch in parameters between my use of HabitEventModel in`ViewHabitActvitiy.java` with the actual `HabitEventModel.java` file. I've made the necessary changes so that the mock data will be shown as expected.
Closes #103

Fix ViewHabitActivity

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitModel.java

Added some comments to habitModel

Added javadoc to habitModel

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTask.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskListener.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManager.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionSpecifier.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DatabaseService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DocumentHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/QueryHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/DocumentModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/MappedModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/ModelMapParser.java

Add an abstraction of the Firestore database to move to later
- Add ServiceTask helper code for handling async tasks
- Add document creating, updating, and getting functionality to database service
Closes #80

Add Database Service

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTask.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskListener.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManager.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionSpecifier.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DatabaseService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DocumentHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/QueryHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/DocumentModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/MappedModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/ModelMapParser.java

Redesign the habit model to use database service
Old HabitModel still exists for legacy sake for now
- Re-implement Habit Model
- Allow pushing model changes to database
- Allow getting model data from database
- Allow creating new habit model and adding to database

Re-design Habit Model

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/BaseController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/ServiceTaskController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTask.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskListener.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManager.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionSpecifier.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DatabaseService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DocumentHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/QueryHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/DocumentModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/MappedModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/ModelMapParser.java

Add three controllers, two are base functionality for the habit controller
Add BaseController
Add HabitController
Add ServiceTaskController
Closes #119

Add BaseController and HabitController

---

src/app/build.gradle
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/BaseController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/ServiceTaskController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTask.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskListener.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManager.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/CollectionSpecifier.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DatabaseService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/DocumentHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/QueryHandle.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/DocumentModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/MappedModelSerializer.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/ModelMapParser.java
src/app/src/main/res/layout/activity_define_habit.xml
src/app/src/main/res/menu/menu_define_habit.xml
src/app/src/main/res/values/strings.xml

Implement DefineHabitActivity
Add DefineHabitActivity to allow for both the creation and editing of a habit
Closes #66

Implement DefineHabitActivity

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java

Fix a bug – the HabitEventModel has changed.

Fix bug - the HabitEventModel has changed

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/DocumentModelSerializer.java

Fix null pointer exception when parsing a null date
Fix null pointer exception when parsing a null date

Fix date parse bug

---

src/app/build.gradle
src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/BottomNavigationTest.java

Intent tests for bottom navigation

---

src/app/build.gradle
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/WeeklyHabitScheduleController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IWeeklyHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/WeeklyHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/HabitScheduleFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/HabitScheduleViewSelector.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/WeeklyHabitScheduleFragment.java
src/app/src/main/res/layout/activity_define_habit.xml
src/app/src/main/res/layout/fragment_weekly_habit_schedule.xml
src/app/src/main/res/values/strings.xml

Add Habit Schedule Views
Add HabitScheduleFragment view to DefineHabitActivity
Add WeeklyHabitScheduleController
Add WeeklyHabitScheduleFragment
Add HabitScheduleViewSelector
Closes #72

Add Habit Schedule View Fragment

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/LoginTest.java

Intent tests for login screen

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/database/serializers/DocumentModelSerializer.java

Add error checked in DefineHabitActivity
- Add error checking for an empty title
- Disable editing of start date if lastCompleted has been set

Add habit title error check

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/AuthorizationService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserLoginActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserRegisterActivity.java

AuthorizationService implemented and user logout implemented. UserLoginActivity and UserRegisterActivity also use AuthorizationService now.
- AuthorizationService
- CurrentUserProfileFragment
- UserLoginActivity 
- UserRegisterActivity 
Closes #46

Authorization service and user logout

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/UserRegisterTest.java

Added sign up intent tests

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/LoginTest.java

Fixed javadoc for the login testing file and formatted the file.
- LoginTest

Fix login testing javadoc

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileTest.java

Profile doesn't currently pull data from firebase so tests will need to be written when that is implemented
Closes #138

Added logging out intent test

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java

Fix deleteHabitEvent

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/AuthorizationServiceTest.java

Unit tests for `AuthorizationService`. Note that the test file is located in the `androidTest` directory because Firebase doesn't work otherwise.
- AuthorizationServiceTest
Closes #139

tests for `AuthorizationService`

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/WeeklyHabitScheduleModelTest.java

Added unit tests for weeklyHabitScheduleModel

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/HabitEventTest.java
src/app/src/main/AndroidManifest.xml
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventActivity.java

Intent test for habit event deletion
Add a new habitevent to be deleted
Click on habitevent
Delete said habit event in habit event details page
Return back to habit list and check that there is one less habit in list

Intent test habitevent deletion

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ExampleActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/FollowingFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/MainActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/SearchFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventActivity.java

Add missing javdocs

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitListController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserHabitCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java

Implemented the HabitListController(will need to be refactored in the future) to fetch all the habits from Firestore.
Linked `DailyHabitFragment` and `CurrentUserProfileFragment`'s ListViews  to the `ViewHabitActivity.java` – the habitID is passed in through intent
Closes #35 
Closes #153 
Closes #151

Habit List

---

src/app/src/main/AndroidManifest.xml
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/AuthorizationService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java

Fix missing import
- ViewHabitActivity
- AndroidManifest

fix missing import

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserHabitCustomList.java

Change opening a habit to be triggered by pressing anywhere on the card rather than the title
- DailyHabitCustomList
- UserHabitCustomList
Closes #164

make pressing a habit more intuitive

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitModel.java

Annotate HabitModel as deprecated

Add Deprecation Annotation to Legacy HabitModel

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java

Link the edit habit button to `DefineHabitActivity.java`

Link the edit habit functionality

---

src/app/src/main/res/layout/activity_view_habit_screen.xml

make habit title in center

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/HabitEventTest.java
src/app/src/main/AndroidManifest.xml
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ExampleActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventActivity.java

Connecting activities related to habit event and testing update scenario
Connected habit event activities together:
adding returns back to the main habit list
updating returns back to the detail habit list
added intent test for updating a habit 
Connected 

Connect habit event to activities and intent test habitevent update

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/services/AuthorizationServiceTest.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserLoginActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserRegisterActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/AuthorizationService.java

Move AuthorizationService to services
- AuthorizationService

move AuthorizationService to services

---

src/app/src/main/AndroidManifest.xml

Fix launch bug

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventTest.java
src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/ViewHabitTest.java

Add intent tests for view habit activity
Check navigation to edit page, ensuring the same values are present on each page
Check navigation to past habit events page

Intent Testing ViewHabitActivity 

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java

Merge issues caused app to break.

bug fix for viewhabitevent

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivity.java

Refactor code

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/HabitEventControllerTest.java

Unit Test HabitEventController using ArrayLists to mock out firebase interactions
Tested creating habit event
Tested updating habit event
Tested reading habit event
Tested deleting habit event

Unit Test HabitEventController

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivityTest.java

Fixed test in defineHabitEventActivity

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivityTest.java

Added intent tests for DefineHabitActivity

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileTest.java

Added profile all habits intent tests

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivityTest.java
src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/HabitEventTest.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventModel.java
src/app/src/main/res/layout/activity_define_habit_event.xml

Fix bug with creating and editing habit events

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/HabitControllerTest.java

Wrote unit tests for HabitController using ArrayList
Closes #176

Add HabitController Unit Tests

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/HabitScheduleModelFactoryTest.java

Test the functions of habit schedule factory

Unit Test HabitSchedulefactory

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileTest.java
src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DailyHabitFragmentTest.java

Changed var name in profile intent test

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventActivity.java

update the habit title as shown in habit event detail page
Pass habit name via intent

update title in habit event with parent habit

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DailyHabitFragmentTest.java

Added dailyHabitFragment intent tests

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventActivity.java

Missing Habit ID connection between 2 activities led to habitid = null in a specific use case
Add id to intent

Habitevent idconnection bug

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IUserModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/UserModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/AuthorizationService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/UserRegisterActivity.java

Add user model and add user register data to database
Add user model
Add user register data to database on commit

add usermodel

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitScheduleModelFactory.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IWeeklyHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/WeeklyHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManager.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/CurrentUserProfileFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/DailyHabitFragment.java

Habits can now be grabbed by only their respective user and by the day they are to be completed
Habits can now be grabbed by only their respective user and by the day they are to be completed
Updated user habit list to only show habits for the given user
Updated daily habit list to only show habits for the given user that are scheduled for that given day
(Sorry, there should be one here but my screen cap ain't working right)
NOTE: habit event tests are broken (will work with owner of those tests to fix)

filter habits by user and schedule

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitActivity.java

Add habit deletion functionality
Add ability to delete habit from ui
on habit delete, delete all associated habit events
Sadly cannot do as screen cap software brokey

Add Delete Habit Functionality

---

src/app/src/main/res/layout/activity_another_user_profile.xml

Created the UI view for another user's profile page.
Closes #211

Add XML file for the profile of another user

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/FollowingFragment.java
src/app/src/main/res/layout/fragment_following.xml

[User following view](https://github.com/CMPUT301F21T09/BudgetProjectName/wiki/User-Interface-Mockups#user-following-screen)
**Using habits as placeholders for users while user-following code is being set up**

User following fragment view

---

src/app/src/main/AndroidManifest.xml
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/UserController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IUserModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/UserModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/AuthorizationService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/AnotherUserProfileActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ExampleActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/CurrentUserProfileFragment.java
src/app/src/main/res/color/requested_button_background_tint.xml
src/app/src/main/res/layout/activity_another_user_profile.xml
src/app/src/main/res/layout/activity_example.xml

Wrote the code needed to fetch user details(name and username) from Firestore and insert them into the `CurrentUserProfileFragment` and `AnotherUserProfileActivity`.
Made changes to `UserModel.java` and `AuthorizationService.java` to include a "Social" Map to be used to store the relationships between users. 
Wrote the code needed to check a few scenarios(whether the logged-in user is/is not following the user on the screen) and display the correct UI accordingly.
Wrote the code that allows the logged-in user to submit a Follow Request to the user on the screen.
Note: A predefined userID is passed in to test the functionalities. 
Request to follow scenario:
The logged-in user is already following the user on the screen (Accepting follow requests is not in this PR. I manually changed the …

Request to follow another user

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/UserCustomList.java

Move UserCustomList to views/lists
Thanks Chee!

Move UserCustomList to proper directory

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
src/app/src/main/res/layout/activity_define_habit.xml
src/app/src/main/res/values/colors.xml
src/app/src/main/res/values/themes.xml

Update DefineHabitActivity UI

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IWeeklyHabitScheduleModel.java

Changed numbering for weeklySchedule

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/UserController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/FollowRequestActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/FollowingFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/FollowRequestCustomList.java
src/app/src/main/res/layout/follow_request_custom_list.xml
src/app/src/main/res/layout/fragment_following.xml

Load all of the incoming follow requests made to the user (social map value 0 or 2) into listview
Added a function to user controller to filter only requests (not users we are following)
Add functionality to the accept button in listview
Updated the database using controller to make changes to the current user's social map and the newly-following users' social map. I followed the accept case detailed in the [design doc](https://docs.google.com/document/d/1AvdjGUVFGz1nljk_wC7BOVH3f-RHT9iHm-OkQ3fQJ_k/edit)
I accept a friend request:
If friend == 0 -> None (Delete my friend in my social map and my friend successfully follows me)
Elif friend == 2 -> 1 (My friend successfully follows me and I continue to follow my friend)
NOTE: I have been testing this on 1 user only (the user who is getting …

Grant follower permissions

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/UserController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/SearchFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/UserCustomList.java
src/app/src/main/res/layout/user_custom_list.xml

Add functionality to be able to find users in search list
Add ability to find users by id
Add ability to find users by id in search list

Find users in search list

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/services/AuthorizationServiceTest.java

Fixed auth test

---

src/app/proguard-rules.pro
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/WeeklyHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java

https://user-images.githubusercontent.com/41885935/143418268-3c90eecf-3fa4-427e-a4d4-e942b3e76e5a.mp4
Closes #55

Added streak functionality

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitActivity.java
src/app/src/main/res/layout/activity_view_habit_screen.xml

Refactored the habit schedule portion of the `ViewHabitActivity.java`. Instead of manually using if conditions to check if a given habit is to be done on each day, the schedule fragment is used. 

Refactor ViewHabitActivity to use the schedule fragment to display the habit schedule

---

src/app/src/main/res/drawable/ic_habit_list_background.xml
src/app/src/main/res/drawable/profile_background_screen.xml
src/app/src/main/res/layout/activity_another_user_profile.xml
src/app/src/main/res/layout/fragment_current_user_profile.xml
src/app/src/main/res/layout/fragment_daily_habit.xml
src/app/src/main/res/layout/fragment_following.xml
src/app/src/main/res/layout/fragment_search.xml

Cleaning up some UI interfaces for my sanity

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/DailyHabitCustomList.java

https://user-images.githubusercontent.com/41885935/143503582-bfdd91d5-04fc-47c5-9e87-e44ef054ce07.mp4

Added habit name to event

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/FollowRequestCustomList.java

- Deny another user from following you by rejecting their follow request
- Add functionality to decline button
- Added additional logic to accept case (should have been done in a separate PR, oops)
- Update firebase with changes as per social map design doc: 
> I deny a friend request:
> If friend == 0 -> None (Delete my friend in my social map because my friend is rejected)
> Elif friend == 2 -> 1 (My friend’s request to follow me cease to exist)
Ben (user id: xXpvWHTq0vPXa1vxCECgX9JvE502) sends me a follow request 
I deny the follow request (sorry Ben)
Ben is removed from my social map.

Deny follower permissions

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/AnotherUserProfileActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitActivity.java

Broke up lines that significantly exceed the vertical line on Android Studio. 

Break up long lines

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/UserController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/FollowRequestActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/FollowingFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/FollowRequestCustomList.java
src/app/src/main/res/layout/follow_custom_list.xml
src/app/src/main/res/layout/fragment_following.xml

Get list of users you are following and view their habits 
Refactor naming of list, user controller functions, etc. to be more general across follower/followee cases

Display following list in following fragment

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/res/layout/activity_define_habit.xml
src/app/src/main/res/values/strings.xml
src/app/src/main/res/values/themes.xml

Functionality for habit privacy done:
- User can set privacy of a habit upon creation
- User can edit privacy of a habit
- User can see public habits of another user they are following
- User cannot see private habits of another user they are following
Left screen: bkong's view of bkong2's profile (bkong can only see bkong2's public habits)
Right screen: bkong2's list of habits (bkong2 can see their public and private habits)
Closes #53 #98 #99

habit privacy functionality

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/UserController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/SearchFragment.java

Search username that starts with user's input
Able to search multiple user
https://user-images.githubusercontent.com/2572832/143561484-dd8015cd-f859-4f40-b24d-a9a83c02769a.mp4

improve user search behaviour

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/FollowTest.java

Template for unit testing functionality to do with following/requesting to follow another user.

Create template file for Unit testing Follows

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/UserModel.java

Added a public constructor in `UserModel.java` to be used in unit tests.
Added an empty constructor so that AuthService will continue to work.

Add public constructor in UserModel

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivityTest.java
src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivityTest.java
src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/HabitEventTest.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/res/layout/activity_define_habit.xml
src/app/src/main/res/layout/activity_define_habit_event.xml
src/app/src/main/res/layout/activity_view_habit_screen.xml
src/app/src/main/res/layout/fragment_daily_habit.xml
src/app/src/main/res/menu/menu_define_habit.xml

Small UI improvements:
- Make location switch blue to be consistent with UI mockups
- Shift checkmark in add/edit habit and add/edit habit event to the left to be consistent with UI mockups
- Fix white line at top of home screen
- Change edit habit button to be closer to UI mockups
Make location switch blue:
Shift checkmark a bit to the left:
Fix white line at top of home screen (Before -> After):
Change edit habit button to be closer to UI mockups:

ui improvements

---

src/app/src/main/res/menu/menu_define_habit.xml

Remove an old file I forgot to delete

cleanup old file

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/FollowRequestTest.java
src/app/src/main/res/layout/fragment_following.xml

-Intent test for clicking follow request button
-Intent test for accepting follow request
-Intent test for denying follow request

Create intent tests for follow requests

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/FollowTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/HabitEventModelTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/HabitScheduleModelFactoryTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/WeeklyHabitScheduleModelTest.java

- test receiving request
- test accepting request
- test denying request
From the perspective of currently signed in user.
Also some small fixes to the habit event test to update a field's type.

Unit test follower request functionality

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/FollowTest.java

- test sending request
- test request is accepted
- test request is denied
From the perspective of currently signed-in user.
Closes #239 
Closes #243 
Closes #245

More follow request unit tests

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/AnotherUserProfileTest.java

Intent test for requesting to follow another user
Closes #238

Intent test for Another user's profile

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java

Fix a display issue when the locality is null
Before (left) and aftter (right)

fix null locality bug

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/UserModelTest.java

write usermodel tests

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivityTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/HabitModelTest.java

Unit and intent tests for setting habit privacy during habit creation/editing
Unit test:
Intent test:
Closes #244

Privacy tests

---

src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/LatLngModelTest.java

Add LatLngModel Tests

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
src/app/src/main/res/layout/activity_view_habit_event.xml

Added top bar and back button functionality

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/BaseController.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/HabitEventControllerTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/controllers/BaseControllerTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/controllers/ServiceTaskControllerTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/models/HabitEventModelTest.java
src/app/src/test/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManagerTest.java

Add many tests
Add tests for:
- ServiceTaskManager + ServiceTask
- ServiceTaskController
- BaseController
Fix HabitEventController tests

Add ServiceTask tests

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitEventController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/ServiceTaskController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/UserController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/FollowRequestActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/DailyHabitFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/SearchFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/WeeklyHabitScheduleFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/DailyHabitCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/FollowRequestCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/HabitEventCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/UserCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/UserHabitCustomList.java

Added missing Javadoc, cleaned up some whitespace/formatting, and removed some unused properties.

add javadoc / remove some unused properties

---

src/app/src/main/res/layout/activity_define_habit_event.xml

Made add/edit habit event screen scrollable.
Closes #236

Make add/edit habit event screen scrollable

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/CustomMapFragment.java
src/app/src/main/res/layout/activity_define_habit_event.xml

Fixed map dragging on add/edit habit event.

fixed map dragging on add/edit habit event

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
src/app/src/main/res/layout/activity_view_habit_event.xml

Prevent NPE when access to location
Set Location text to "No Address Found" when there is no country info
Reorder layout to show image properly in ViewHabitEventActivity

Location Bug fix & Image bug fix

---

.github/workflows/android.yml

fix github actions

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/MainActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitScheduleModelFactory.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/AuthorizationService.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/services/ServiceTaskManager.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/AnotherUserProfileActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/CurrentUserProfileFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/CustomMapFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/DailyHabitFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/SearchFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/DailyHabitCustomList.java
src/app/src/main/res/layout/fragment_following.xml

No more relaunching activity to refreshing views by using onResume() :)
- DailyHabitFragment
- ViewHabitActivity || Now we can back to ViewHabitAcitvity after edit habit
- ViewHabitEventActivity
Fix SearchFragment UI bug
Fix WeeklySchdule was editable in ViewHabitActivity
Clean up
https://user-images.githubusercontent.com/2572832/143862010-e46979c6-7fbb-43bf-aee2-3ce689bd0fdd.mp4

Use onResume() instead of intent.flag_activity_clear_top to reload stuff

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java

https://user-images.githubusercontent.com/41885935/143938526-ec5ab7fd-0ee8-4a6b-835e-f9506e54eea1.mp4

Habits that have been completed are removed from daily list

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java

add security exception checks

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java

Add security checks

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/FollowRequestActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/FollowingFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/FollowCustomList.java

- Rename list class to make it more generalized
- Add private access modifiers to all class attributes

Update Follow files to match UML

---

src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivityTest.java

Start at MainActivity instead of DefineHabitEventActivity
NOTE: assume signed in user has 1 habit in their daily habit list to click

fix definehabiteventactivitytest

---

src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/BaseController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitScheduleModelFactory.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitScheduleModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IUserModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/UserModel.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/fragments/SearchFragment.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/FollowCustomList.java
src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/lists/UserCustomList.java

final code formatting
